name: CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697
        with:
          source: .
          destination: ./_site

      - name: Prove generated homepage is nonempty
        run: test -s ./_site/index.html
